# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanager', '0005_auto_20171214_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='42', unique=True),
        ),
    ]
